import type {
  Agency,
  AdminProperty,
  Investor,
  Transaction,
  OverviewStats,
  FundingPoint,
  Notification,
  AdminSettings,
} from "@/features/admin/schemas";

export const adminProfile: AdminSettings = {
  platformName: "Roova",
  supportEmail: "support@roova.com",
  defaultCommissionPct: 3.5,
};

export const agencies: Agency[] = [
  {
    id: "adunni-properties",
    name: "Adunni Properties",
    tier: "Gold tier",
    status: "active",
    email: "hello@adunniproperties.com",
    joinedAt: "2025-08-01",
    propertiesCount: 5,
    totalRaised: 638_000_000,
    investorsCount: 312,
    commissionEarned: 18_795_000,
  },
  {
    id: "capital-estates-ltd",
    name: "Capital Estates Ltd",
    tier: "Silver tier",
    status: "active",
    email: "contact@capitalestates.ng",
    joinedAt: "2025-09-15",
    propertiesCount: 3,
    totalRaised: 210_000_000,
    investorsCount: 120,
    commissionEarned: 6_500_000,
  },
  {
    id: "sterling-heights-realty",
    name: "Sterling Heights Realty",
    tier: "Gold tier",
    status: "active",
    email: "info@sterlingheights.ng",
    joinedAt: "2025-06-10",
    propertiesCount: 4,
    totalRaised: 480_000_000,
    investorsCount: 210,
    commissionEarned: 15_200_000,
  },
  {
    id: "northshore-homes",
    name: "Northshore Homes",
    tier: "Unranked",
    status: "pending",
    email: "team@northshorehomes.ng",
    joinedAt: "2026-06-28",
    propertiesCount: 0,
    totalRaised: 0,
    investorsCount: 0,
    commissionEarned: 0,
  },
  {
    id: "prime-realty-ng",
    name: "Prime Realty NG",
    tier: "Silver tier",
    status: "active",
    email: "hello@primerealty.ng",
    joinedAt: "2025-12-01",
    propertiesCount: 2,
    totalRaised: 95_000_000,
    investorsCount: 58,
    commissionEarned: 2_900_000,
  },
  {
    id: "horizon-properties",
    name: "Horizon Properties",
    tier: "Gold tier",
    status: "suspended",
    email: "contact@horizonproperties.ng",
    joinedAt: "2025-05-20",
    propertiesCount: 3,
    totalRaised: 150_000_000,
    investorsCount: 88,
    commissionEarned: 4_100_000,
  },
];

export const properties: AdminProperty[] = [
  {
    id: "eko-atlantic-tower",
    title: "Eko Atlantic Skyline Tower",
    location: "Victoria Island, Lagos",
    agencyName: "Sterling Heights Realty",
    tier: "Gold tier",
    status: "live",
    yieldPct: 14.2,
    raised: 391_500_000,
    target: 450_000_000,
    investors: 39,
    sharePrice: 50_000,
    submittedAt: "2026-03-01",
  },
  {
    id: "lekki-phase-1",
    title: "Lekki Phase 1 Residences",
    location: "Lekki, Lagos",
    agencyName: "Adunni Properties",
    tier: "Gold tier",
    status: "live",
    yieldPct: 11.8,
    raised: 182_000_000,
    target: 240_000_000,
    investors: 64,
    sharePrice: 50_000,
    submittedAt: "2026-03-02",
  },
  {
    id: "ikoyi-waterfront-lofts",
    title: "Ikoyi Waterfront Lofts",
    location: "Ikoyi, Lagos",
    agencyName: "Sterling Heights Realty",
    tier: "Gold tier",
    status: "live",
    yieldPct: 13.4,
    raised: 305_000_000,
    target: 320_000_000,
    investors: 88,
    sharePrice: 50_000,
    submittedAt: "2026-02-15",
  },
  {
    id: "maitama-garden-court",
    title: "Maitama Garden Court",
    location: "Maitama, Abuja",
    agencyName: "Capital Estates Ltd",
    tier: "Silver tier",
    status: "live",
    yieldPct: 9.6,
    raised: 98_000_000,
    target: 150_000_000,
    investors: 41,
    sharePrice: 50_000,
    submittedAt: "2026-04-01",
  },
  {
    id: "surulere-court-residences",
    title: "Surulere Court Residences",
    location: "Surulere, Lagos",
    agencyName: "Adunni Properties",
    tier: "Silver tier",
    status: "funded",
    yieldPct: 9.8,
    raised: 150_000_000,
    target: 150_000_000,
    investors: 112,
    sharePrice: 50_000,
    submittedAt: "2025-11-20",
  },
  {
    id: "ajah-garden-estate",
    title: "Ajah Garden Estate",
    location: "Ajah, Lagos",
    agencyName: "Adunni Properties",
    tier: "Gold tier",
    status: "funded",
    yieldPct: 13.1,
    raised: 210_000_000,
    target: 210_000_000,
    investors: 98,
    sharePrice: 50_000,
    submittedAt: "2025-09-05",
  },
  {
    id: "yaba-heights",
    title: "Yaba Heights Apartments",
    location: "Yaba, Lagos",
    agencyName: "Prime Realty NG",
    tier: "Silver tier",
    status: "draft",
    yieldPct: 10.4,
    raised: 0,
    target: 120_000_000,
    investors: 0,
    sharePrice: 50_000,
    submittedAt: "2026-06-30",
  },
  {
    id: "gwarinpa-court",
    title: "Gwarinpa Court",
    location: "Gwarinpa, Abuja",
    agencyName: "Capital Estates Ltd",
    tier: "Silver tier",
    status: "draft",
    yieldPct: 10.0,
    raised: 0,
    target: 130_000_000,
    investors: 0,
    sharePrice: 50_000,
    submittedAt: "2026-07-01",
  },
  {
    id: "victoria-crest-towers",
    title: "Victoria Crest Towers",
    location: "Victoria Island, Lagos",
    agencyName: "Horizon Properties",
    tier: "Gold tier",
    status: "rejected",
    yieldPct: 8.5,
    raised: 0,
    target: 300_000_000,
    investors: 0,
    sharePrice: 50_000,
    submittedAt: "2026-05-10",
  },
  {
    id: "asokoro-view",
    title: "Asokoro View Residences",
    location: "Asokoro, Abuja",
    agencyName: "Prime Realty NG",
    tier: "Gold tier",
    status: "rejected",
    yieldPct: 15.0,
    raised: 0,
    target: 500_000_000,
    investors: 0,
    sharePrice: 50_000,
    submittedAt: "2026-06-01",
  },
];

export const overviewStats: OverviewStats = {
  totalRaised: properties.reduce((sum, p) => sum + p.raised, 0),
  totalAgencies: agencies.length,
  totalProperties: properties.length,
  totalInvestors: properties.reduce((sum, p) => sum + p.investors, 0),
  platformRevenue: 14_250_000,
  pendingApprovals:
    agencies.filter((a) => a.status === "pending").length +
    properties.filter((p) => p.status === "draft").length,
};

const MONTHS = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];

const MONTHLY_FUNDING = [
  65_000_000, 78_000_000, 92_000_000, 85_000_000, 110_000_000, 125_000_000, 140_000_000,
  132_000_000, 158_000_000, 149_000_000, 172_000_000, 165_000_000,
];

export const fundingSeries: FundingPoint[] = MONTHS.map((month, index) => ({
  month,
  amount: MONTHLY_FUNDING[index],
}));

export const investors: Investor[] = [
  {
    id: "inv_1",
    name: "Chidinma Okafor",
    email: "chidinma.okafor@example.com",
    kycStatus: "verified",
    totalInvested: 2_450_000,
    propertiesCount: 3,
    joinedAt: "2025-09-10",
  },
  {
    id: "inv_2",
    name: "Tunde Bakare",
    email: "tunde.bakare@example.com",
    kycStatus: "verified",
    totalInvested: 5_600_000,
    propertiesCount: 5,
    joinedAt: "2025-07-22",
  },
  {
    id: "inv_3",
    name: "Grace Okonkwo",
    email: "grace.okonkwo@example.com",
    kycStatus: "pending",
    totalInvested: 250_000,
    propertiesCount: 1,
    joinedAt: "2026-06-28",
  },
  {
    id: "inv_4",
    name: "David Okoro",
    email: "david.okoro@example.com",
    kycStatus: "verified",
    totalInvested: 3_200_000,
    propertiesCount: 4,
    joinedAt: "2025-11-05",
  },
  {
    id: "inv_5",
    name: "Fatima Bello",
    email: "fatima.bello@example.com",
    kycStatus: "verified",
    totalInvested: 1_150_000,
    propertiesCount: 2,
    joinedAt: "2026-01-15",
  },
  {
    id: "inv_6",
    name: "Yusuf Abdullahi",
    email: "yusuf.abdullahi@example.com",
    kycStatus: "rejected",
    totalInvested: 0,
    propertiesCount: 0,
    joinedAt: "2026-06-30",
  },
  {
    id: "inv_7",
    name: "Aisha Mohammed",
    email: "aisha.mohammed@example.com",
    kycStatus: "pending",
    totalInvested: 500_000,
    propertiesCount: 1,
    joinedAt: "2026-06-25",
  },
  {
    id: "inv_8",
    name: "Segun Adeyemi",
    email: "segun.adeyemi@example.com",
    kycStatus: "verified",
    totalInvested: 8_900_000,
    propertiesCount: 6,
    joinedAt: "2025-06-01",
  },
];

export const transactions: Transaction[] = [
  {
    id: "tx_1",
    type: "investment",
    party: "Chidinma Okafor",
    amount: 2_450_000,
    date: "2026-06-28",
    status: "completed",
  },
  {
    id: "tx_2",
    type: "commission_payout",
    party: "Adunni Properties",
    amount: 2_380_000,
    date: "2026-06-30",
    status: "completed",
  },
  {
    id: "tx_3",
    type: "investment",
    party: "Tunde Bakare",
    amount: 1_200_000,
    date: "2026-06-27",
    status: "completed",
  },
  {
    id: "tx_4",
    type: "dividend_payout",
    party: "David Okoro",
    amount: 145_000,
    date: "2026-06-25",
    status: "completed",
  },
  {
    id: "tx_5",
    type: "commission_payout",
    party: "Sterling Heights Realty",
    amount: 3_050_000,
    date: "2026-06-30",
    status: "completed",
  },
  {
    id: "tx_6",
    type: "investment",
    party: "Fatima Bello",
    amount: 850_000,
    date: "2026-06-24",
    status: "completed",
  },
  {
    id: "tx_7",
    type: "withdrawal",
    party: "Segun Adeyemi",
    amount: 500_000,
    date: "2026-06-20",
    status: "completed",
  },
  {
    id: "tx_8",
    type: "commission_payout",
    party: "Capital Estates Ltd",
    amount: 980_000,
    date: "2026-06-30",
    status: "pending",
  },
  {
    id: "tx_9",
    type: "investment",
    party: "Grace Okonkwo",
    amount: 250_000,
    date: "2026-06-28",
    status: "completed",
  },
  {
    id: "tx_10",
    type: "dividend_payout",
    party: "Chidinma Okafor",
    amount: 62_000,
    date: "2026-06-15",
    status: "completed",
  },
  {
    id: "tx_11",
    type: "investment",
    party: "Aisha Mohammed",
    amount: 500_000,
    date: "2026-06-25",
    status: "pending",
  },
  {
    id: "tx_12",
    type: "commission_payout",
    party: "Prime Realty NG",
    amount: 410_000,
    date: "2026-06-30",
    status: "completed",
  },
];

export const notifications: Notification[] = [
  {
    id: "n1",
    type: "agency_application",
    title: "New agency application: Northshore Homes",
    message: "Northshore Homes has applied to list properties on Roova.",
    timestamp: "2026-07-02T10:00:00Z",
    read: false,
  },
  {
    id: "n2",
    type: "property_submitted",
    title: "New listing submitted: Gwarinpa Court",
    message: "Capital Estates Ltd submitted a new property for review.",
    timestamp: "2026-07-01T15:30:00Z",
    read: false,
  },
  {
    id: "n3",
    type: "kyc_flagged",
    title: "KYC flagged: Yusuf Abdullahi",
    message: "Document mismatch detected during identity verification.",
    timestamp: "2026-06-30T09:00:00Z",
    read: false,
  },
  {
    id: "n4",
    type: "large_transaction",
    title: "Large investment recorded",
    message: "Segun Adeyemi invested ₦8,900,000 in total across 6 properties.",
    timestamp: "2026-06-29T12:00:00Z",
    read: false,
  },
  {
    id: "n5",
    type: "property_submitted",
    title: "New listing submitted: Yaba Heights Apartments",
    message: "Prime Realty NG submitted a new property for review.",
    timestamp: "2026-06-30T11:00:00Z",
    read: true,
  },
  {
    id: "n6",
    type: "system",
    title: "Monthly payout run completed",
    message: "₦6,820,000 in commission payouts were processed for June.",
    timestamp: "2026-06-30T18:00:00Z",
    read: true,
  },
  {
    id: "n7",
    type: "agency_application",
    title: "Agency suspended: Horizon Properties",
    message: "Horizon Properties was suspended pending compliance review.",
    timestamp: "2026-06-15T09:00:00Z",
    read: true,
  },
  {
    id: "n8",
    type: "system",
    title: "Welcome to Roova Admin",
    message: "You have full oversight of agencies, listings, investors and transactions.",
    timestamp: "2026-05-01T09:00:00Z",
    read: true,
  },
];
